<?php
/**
 *
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2016
 *
 * @link      https://www.github.com/janhuang
 * @link      http://www.fast-d.cn/
 */

namespace FastD\Http\Bag;

/**
 * Class HeaderBag
 *
 * @package FastD\Http\Bag
 */
class HeaderBag extends Bag
{
    /**
     * HeaderBag constructor.
     *
     * @param array $bag
     */
    public function __construct(array $bag)
    {
        $headers = [];

        array_walk($bag, function ($value, $key) use (&$headers) {
            if (0 === strpos($key, 'HTTP_')) {
                $headers[substr($key, 5)] = explode(',', $value);
            }
        });

        parent::__construct($headers);
    }

    /**
     * @param $name
     * @param bool $raw
     * @param null $callback
     * @return mixed|string
     */
    public function get($name, $raw = false, $callback = null)
    {
        return parent::get(strtoupper($name), $raw, $callback); // TODO: Change the autogenerated stub
    }

    /**
     * @return null|string
     */
    public function getUserAgent()
    {
        return $this->hasGet('USER_AGENT', null);
    }

    /**
     * @return null|string
     */
    public function getAccept()
    {
        return $this->hasGet('ACCEPT', null);
    }

    /**
     * @return null|string
     */
    public function getAcceptEncoding()
    {
        return $this->hasGet('ACCEPT_ENCODING', null);
    }

    /**
     * @return null|string
     */
    public function getAcceptLanguage()
    {
        return $this->hasGet('ACCEPT_LANGUAGE', null);
    }

    /**
     * @return null|string
     */
    public function getReferer()
    {
        return $this->hasGet('REFERER', null);
    }

    /**
     * @return null|string
     */
    public function getHost()
    {
        return $this->hasGet('HOST', null);
    }

    /**
     * @return null|string
     */
    public function getConnection()
    {
        return $this->hasGet('CONNECTION', null);
    }

    /**
     * @return null|string
     */
    public function getCacheControl()
    {
        return $this->hasGet('CACHE_CONTROL', null);
    }

    /**
     * @return bool
     */
    public function isXmlHttpRequest()
    {
        return 'xmlhttprequest' === strtolower($this->hasGet('X_REQUESTED_WITH', ''));
    }

    /**
     * @return string
     */
    public function getClientIp()
    {
        foreach ([
                     'CLIENT_IP',
                     'X_FORWARDED_FOR',
                     'X_FORWARDED',
                     'FORWARDED_FOR',
                     'FORWARDED',
                     'REMOTE_ADDR'
                 ] as $value) {
            if ($this->has($value)) {
                return $this->get($value);
            }
        }

        return 'unknown';
    }

    /**
     * Return http response header.
     *
     * @return string
     */
    public function __toString()
    {
        $header = '';

        foreach ($this->all() as $name => $value) {
            $header .= sprintf('%s: %s', $name, $value) . "\r\n";
        }

        return $header;
    }
}